group:
  student: STUDENT
  lecturer: LECTURER

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${server.port}
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
    hostname: ${spring.application.name}
