server:
  port: 8082

spring:
  application:
    name: university-service
  config:
    import:
      - vault://secret/spring-boot-lms
      - configserver:http://config-server:8888

  kafka:
    producer:
      bootstrap-servers: apache-kafka:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
