server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          default-label: configs
          uri: https://github.com/avishka2k/lms-microservices.git
          clone-on-start: true